version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kober
      MYSQL_DATABASE: itl_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  my_rest_api:
    build: C:\Users\kober\source\repos\linux prueba\linux prueba
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
