version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kober
      MYSQL_DATABASE: itl_db
    ports:
      - "3306:3306"  # Mapea el puerto del contenedor al puerto del host

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mapea el puerto del contenedor al puerto del host
    depends_on:
      - mysql
